version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      - NODE_ENV=${NODE_ENV}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      #- GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - GENERIC_TIMEZONE=Asia/Jakarta
      - DB_TYPE=${DB_TYPE}
      # if using mysql
      - DB_MYSQLDB_HOST=${DB_MYSQLDB_HOST}
      - DB_MYSQLDB_PORT=${DB_MYSQLDB_PORT}
      - DB_MYSQLDB_DATABASE=${DB_MYSQLDB_DATABASE}
      - DB_MYSQLDB_USER=${DB_MYSQLDB_USER}
      - DB_MYSQLDB_PASSWORD=${DB_MYSQLDB_PASSWORD}
      # if using postgres
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_TRUSTED_PROXY_LIST=${N8N_TRUSTED_PROXY_LIST}
      - EXPRESS_TRUST_PROXY=true
      - N8N_PROXY_HOPS=1
      - N8N_PUSH_BACKEND=sse
      # EMAIL
      - N8N_EMAIL_MODE=${N8N_EMAIL_MODE}
      - N8N_SMTP_HOST=${N8N_SMTP_HOST}
      - N8N_SMTP_PORT=${N8N_SMTP_PORT}
      - N8N_SMTP_USER=${N8N_SMTP_USER}
      - N8N_SMTP_PASS=${N8N_SMTP_PASS}
      - N8N_SMTP_SENDER=${N8N_SMTP_SENDER}
      - N8N_SMTP_SSL=${N8N_SMTP_SSL}
    extra_hosts:
       - "host.docker.internal:host-gateway"
    volumes:
      - ${PWD}/.n8n:/home/node/.n8n

